jobs:
- job: CodeScene
  condition: and(succeeded(), eq(variables['CodeScene'], 'true'))
  dependsOn: Build
  pool:
    name:  '$(PoolName)'
    demands:
    - pdp -equals $(DemandValue)
  steps:
  - checkout: none
  - task: CmdLine@2
    displayName: CodeScene
    inputs:
     script: 'echo CodeScene'
