jobs:
- job: FanOut
  condition: and(succeeded(), eq(variables['FanOut'], 'true'))
  dependsOn: Build
  pool:
    name:  '$(PoolName)'
    demands:
    - pdp -equals $(DemandValue)
  steps:
  - checkout: none
  - task: CmdLine@2
    displayName: FanOut_TICS
    inputs:
     script: 'echo FanOut_TICS'
