jobs:
- job: ProjSpec_CompilerWarnings
  condition: and(succeeded(), eq(variables['ProjSpec_CompilerWarnings'], 'true'))
  dependsOn: Build
  pool:
    name:  '$(PoolName)'
    demands:
    - pdp -equals $(DemandValue)
  steps:
  - checkout: none
  - task: CmdLine@1
    displayName: 'Gate: Build Quality check'
    inputs:
     filename: '"$(EGS.filename)" '
     arguments: '$(EGS.MainDll) $(EGS.configjson) -p $(System.PullRequest.PullRequestId) -d -gateon cwcheck -biu $(EGS.BIU) -buildid $(Build.BuildId)'
    enabled: 'true'
