jobs:
- job: PRSize
  condition: and(succeeded(), eq(variables['PRSize'], 'true'))
  dependsOn: Project_Settings
  pool:
    name:  '$(PoolName)'
    demands:
    - pdp -equals $(DemandValue)
  steps:
  - checkout: none
  - task: CmdLine@1
    displayName: 'Gate: PRSize'
    inputs:
     filename: '"$(EGS.filename)" '
     arguments: '$(EGS.MainDll) $(EGS.configjson) -p $(System.PullRequest.PullRequestId) -gateon prfilesize -biu $(EGS.BIU) -w $(Build.sourcesdirectory) -d '  
    enabled: 'true'
