jobs:
- job: SecurityCheck
  condition: and(succeeded(), eq(variables['SecurityCheck'], 'true'))
  dependsOn: Build
  pool:
    name:  '$(PoolName)'
    demands:
    - pdp -equals $(DemandValue)
  steps:
  - checkout: none
  - task: CmdLine@2
    displayName: SecurityCheck
    inputs:
     script: 'echo SecurityCheck'
